 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
/home/melancholiac/web-proj
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
/home/melancholiac/web-proj
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
/home/melancholiac/web-proj
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Apr/2017 21:39:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2017 21:39:20] "GET /sign_up HTTP/1.1" 200 -
[2017-04-18 21:39:24,563] ERROR in app: Exception on /sign_up [POST]
Traceback (most recent call last):
  File "/home/melancholiac/web-proj/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/melancholiac/web-proj/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/melancholiac/web-proj/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/melancholiac/web-proj/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/melancholiac/web-proj/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/melancholiac/web-proj/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/melancholiac/web-proj/yafr/main.py", line 184, in sign_up
    cur.execute("SELECT count(*) FROM users WHERE username = ?", (username,))
sqlite3.OperationalError: no such table: users
127.0.0.1 - - [18/Apr/2017 21:39:24] "POST /sign_up HTTP/1.1" 500 -
/home/melancholiac/web-proj
